//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McTools.Xrm.Connection.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McTools.Xrm.Connection.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please wait while the wizard is trying to connect to your Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_ConnectingHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_ConnectingHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter credentials required to connect to Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_CredentialsHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_CredentialsHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the url displayed in the browser when you are connected to your Microsoft Dynamics CRM organization.
        /// </summary>
        internal static string ConnectionWizard_EnterUrlHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_EnterUrlHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your information have not been validated.
        /// </summary>
        internal static string ConnectionWizard_ErrorHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_ErrorHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help us to determine if your Microsoft Dynamics CRM deployment is exposed via IFD.
        /// </summary>
        internal static string ConnectionWizard_IfdSelectionHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_IfdSelectionHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The url you specified does not look like a valid url for an IFD deployment. Please correct the url.
        /// </summary>
        internal static string ConnectionWizard_InvalidIfUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidIfUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong timeout value!
        ///
        ///Expected format : HH:mm:ss.
        /// </summary>
        internal static string ConnectionWizard_InvalidTimeoutValue {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidTimeoutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The url you specified is invalid!.
        /// </summary>
        internal static string ConnectionWizard_InvalidUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You changed some values that require to test the connection. Would you like to test it now?
        ///
        ///Note that this is required to validate this wizard.
        /// </summary>
        internal static string ConnectionWizard_NeedToTestConnectionAgain {
            get {
                return ResourceManager.GetString("ConnectionWizard_NeedToTestConnectionAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your credentials before trying to connect.
        /// </summary>
        internal static string ConnectionWizard_PleaseEnterCredentials {
            get {
                return ResourceManager.GetString("ConnectionWizard_PleaseEnterCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        internal static string ConnectionWizard_QuestionHeaderTitle {
            get {
                return ResourceManager.GetString("ConnectionWizard_QuestionHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your information have been validated.
        /// </summary>
        internal static string ConnectionWizard_SuccessHeaderDescription {
            get {
                return ResourceManager.GetString("ConnectionWizard_SuccessHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We were unable to determine the organization name based on the information you specified. Please complete the url to add the organization name inside.
        /// </summary>
        internal static string ConnectionWizard_UnableToDetermineOrganization {
            get {
                return ResourceManager.GetString("ConnectionWizard_UnableToDetermineOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to identify organization from url, please review it!.
        /// </summary>
        internal static string ConnectionWizard_UnableToDetermineOrganizationFromUrl {
            get {
                return ResourceManager.GetString("ConnectionWizard_UnableToDetermineOrganizationFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string ConnectionWizard_WarningTitle {
            get {
                return ResourceManager.GetString("ConnectionWizard_WarningTitle", resourceCulture);
            }
        }
    }
}
